import React from 'react';
import { ArrowLeft, Shield, Scale, Info, MessageCircle, AlertTriangle } from 'lucide-react';

interface TermsViewProps {
  onBack: () => void;
}

const TermsView: React.FC<TermsViewProps> = ({ onBack }) => {
  return (
    <div className="min-h-screen bg-white animate-in fade-in duration-500 overflow-y-auto">
      <div className="max-w-3xl mx-auto px-6 py-12 sm:py-20">
        
        {/* Navigation */}
        <button 
          onClick={onBack}
          className="flex items-center gap-2 text-slate-500 hover:text-indigo-600 font-semibold mb-10 transition-colors group"
        >
          <ArrowLeft className="w-5 h-5 group-hover:-translate-x-1 transition-transform" />
          Back to App
        </button>

        {/* Header */}
        <header className="mb-12 border-b border-slate-100 pb-10">
          <h1 className="text-4xl font-extrabold text-slate-900 tracking-tight mb-4">
            Terms & Conditions
          </h1>
          <p className="text-lg text-slate-500 font-medium">
            Last updated: May 2024. Simple terms for a simple project.
          </p>
        </header>

        {/* Content Sections */}
        <div className="space-y-12">
          
          <section className="space-y-4">
            <div className="flex items-center gap-3 text-indigo-600">
              <Info className="w-6 h-6" />
              <h2 className="text-xl font-bold">1. Project Overview</h2>
            </div>
            <p className="text-slate-600 leading-relaxed">
              <strong>AI-Powered Micro-Innovation Advisor</strong> is an educational demo built to help students and early-stage builders. It is intended for experimentation and creative brainstorming. It is not a professional business consulting service.
            </p>
          </section>

          <section className="space-y-4">
            <div className="flex items-center gap-3 text-indigo-600">
              <Shield className="w-6 h-6" />
              <h2 className="text-xl font-bold">2. Data & Privacy</h2>
            </div>
            <p className="text-slate-600 leading-relaxed">
              We value your privacy. This application is a "stateless" demo:
            </p>
            <ul className="list-disc pl-5 space-y-2 text-slate-600">
              <li>We do <strong>not</strong> store your chat history on any persistent database.</li>
              <li>We do <strong>not</strong> sell or share your email address.</li>
              <li>All processing is done via the Google Gemini API. Your inputs are subject to Google's Privacy Policy.</li>
            </ul>
          </section>

          <section className="space-y-4">
            <div className="flex items-center gap-3 text-indigo-600">
              <MessageCircle className="w-6 h-6" />
              <h2 className="text-xl font-bold">3. AI Content Disclaimer</h2>
            </div>
            <p className="text-slate-600 leading-relaxed">
              The suggestions provided are generated by an Artificial Intelligence. AI can sometimes generate inaccurate, biased, or nonsensical information (hallucinations). 
            </p>
            <div className="p-4 bg-amber-50 rounded-xl border border-amber-100 flex gap-3">
              <AlertTriangle className="w-5 h-5 text-amber-600 flex-shrink-0" />
              <p className="text-sm text-amber-800 font-medium">
                Always use your own judgment before implementing any advice or code generated by this advisor.
              </p>
            </div>
          </section>

          <section className="space-y-4">
            <div className="flex items-center gap-3 text-indigo-600">
              <Scale className="w-6 h-6" />
              <h2 className="text-xl font-bold">4. User Conduct</h2>
            </div>
            <p className="text-slate-600 leading-relaxed">
              Please use this tool responsibly. Do not input sensitive personal data, proprietary corporate secrets, or illegal content. Be kind to the AI (even if it's just a machine).
            </p>
          </section>

          <section className="space-y-4 border-t border-slate-100 pt-10">
            <h2 className="text-xl font-bold text-slate-900">Contact</h2>
            <p className="text-slate-600 leading-relaxed">
              Since this is a student project, official support is not provided. However, feel free to reach out to the project maintainers via the GitHub repository where this code is hosted.
            </p>
          </section>

        </div>

        {/* Footer */}
        <footer className="mt-20 pt-8 border-t border-slate-100 text-center">
          <p className="text-sm text-slate-400 font-medium">
            &copy; 2024 AI-Powered Micro-Innovation Advisor. Built for builders.
          </p>
        </footer>

      </div>
    </div>
  );
};

export default TermsView;